apiVersion: v1
kind: Secret
metadata:
  name: lodestar-secret
  labels:
    app: lodestar
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres_password"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"
  ALERTS_IN_UA_TOKEN: ""
