-- V1__init_schema.sql: Initial relational schema for alert event archiving and subscriptions

CREATE TABLE IF NOT EXISTS alert_events_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    kafka_topic VARCHAR(255) NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_alert_history_region_ts ON alert_events_history(region_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_alert_history_event_id ON alert_events_history(event_id);

CREATE TABLE IF NOT EXISTS alert_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    recipient_address VARCHAR(255) NOT NULL,
    region_id VARCHAR(255) NOT NULL,
    min_severity VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscription_region ON alert_subscriptions(region_id);
CREATE INDEX IF NOT EXISTS idx_subscription_recipient_channel ON alert_subscriptions(recipient_address, channel);
CREATE INDEX IF NOT EXISTS idx_subscription_user_id ON alert_subscriptions(user_id);
