-- V2__create_anomaly_history.sql: Relational schema for storing detected stream anomalies

CREATE TABLE IF NOT EXISTS anomaly_events_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anomaly_id VARCHAR(255) NOT NULL,
    region_id VARCHAR(255) NOT NULL,
    anomaly_type VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    event_count INTEGER NOT NULL,
    window_duration_seconds BIGINT NOT NULL,
    severity VARCHAR(50) NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_anomaly_history_region_ts ON anomaly_events_history(region_id, detected_at);
CREATE INDEX IF NOT EXISTS idx_anomaly_history_id ON anomaly_events_history(anomaly_id);
