-- V3__create_region_mappings.sql: Relational tables for canonical regions, normalization mappings, and unrecognized location tracking

CREATE TABLE IF NOT EXISTS canonical_regions (
    region_id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS region_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_title VARCHAR(255) NOT NULL UNIQUE,
    region_id VARCHAR(64) NOT NULL REFERENCES canonical_regions(region_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_region_mappings_raw_title ON region_mappings(raw_title);
CREATE INDEX IF NOT EXISTS idx_region_mappings_region_id ON region_mappings(region_id);

CREATE TABLE IF NOT EXISTS unrecognized_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_title VARCHAR(255) NOT NULL UNIQUE,
    occurrences_count BIGINT NOT NULL DEFAULT 1,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_unrecognized_locations_title ON unrecognized_locations(raw_title);

-- Seed canonical regions
INSERT INTO canonical_regions (region_id, display_name) VALUES
    ('KYIV_REGION', 'Київська область та м. Київ'),
    ('LVIV_REGION', 'Львівська область'),
    ('KHARKIV_REGION', 'Харківська область'),
    ('ODESA_REGION', 'Одеська область'),
    ('DNIPRO_REGION', 'Дніпропетровська область'),
    ('ZAPORIZHZHIA_REGION', 'Запорізька область'),
    ('MYKOLAIV_REGION', 'Миколаївська область'),
    ('POLTAVA_REGION', 'Полтавська область'),
    ('VINNYTSIA_REGION', 'Вінницька область'),
    ('CHERKASY_REGION', 'Черкаська область'),
    ('CHERNIHIV_REGION', 'Чернігівська область'),
    ('SUMY_REGION', 'Сумська область'),
    ('ZHYTOMYR_REGION', 'Житомирська область'),
    ('KHMELNYTSKYI_REGION', 'Хмельницька область'),
    ('RIVNE_REGION', 'Рівненська область'),
    ('VOLYN_REGION', 'Волинська область'),
    ('IVANO_FRANKIVSK_REGION', 'Івано-Франківська область'),
    ('TERNOPIL_REGION', 'Тернопільська область'),
    ('ZAKARPATTIA_REGION', 'Закарпатська область'),
    ('CHERNIVTSI_REGION', 'Чернівецька область'),
    ('KIROVOHRAD_REGION', 'Кіровоградська область'),
    ('KHERSON_REGION', 'Херсонська область'),
    ('DONETSK_REGION', 'Донецька область'),
    ('LUHANSK_REGION', 'Луганська область'),
    ('CRIMEA_REGION', 'АР Крим та м. Севастополь');

-- Seed known aliases into region_mappings (normalized lowercase)
INSERT INTO region_mappings (raw_title, region_id) VALUES
    ('м. київ', 'KYIV_REGION'),
    ('київ', 'KYIV_REGION'),
    ('київська область', 'KYIV_REGION'),
    ('київська', 'KYIV_REGION'),
    ('львівська область', 'LVIV_REGION'),
    ('львівська', 'LVIV_REGION'),
    ('м. львів', 'LVIV_REGION'),
    ('харківська область', 'KHARKIV_REGION'),
    ('харківська', 'KHARKIV_REGION'),
    ('м. харків', 'KHARKIV_REGION'),
    ('одеська область', 'ODESA_REGION'),
    ('одеська', 'ODESA_REGION'),
    ('м. одеса', 'ODESA_REGION'),
    ('дніпропетровська область', 'DNIPRO_REGION'),
    ('дніпропетровська', 'DNIPRO_REGION'),
    ('м. дніпро', 'DNIPRO_REGION'),
    ('запорізька область', 'ZAPORIZHZHIA_REGION'),
    ('запорізька', 'ZAPORIZHZHIA_REGION'),
    ('миколаївська область', 'MYKOLAIV_REGION'),
    ('миколаївська', 'MYKOLAIV_REGION'),
    ('полтавська область', 'POLTAVA_REGION'),
    ('полтавська', 'POLTAVA_REGION'),
    ('вінницька область', 'VINNYTSIA_REGION'),
    ('вінницька', 'VINNYTSIA_REGION'),
    ('черкаська область', 'CHERKASY_REGION'),
    ('черкаська', 'CHERKASY_REGION'),
    ('чернігівська область', 'CHERNIHIV_REGION'),
    ('чернігівська', 'CHERNIHIV_REGION'),
    ('сумська область', 'SUMY_REGION'),
    ('сумська', 'SUMY_REGION'),
    ('житомирська область', 'ZHYTOMYR_REGION'),
    ('житомирська', 'ZHYTOMYR_REGION'),
    ('хмельницька область', 'KHMELNYTSKYI_REGION'),
    ('хмельницька', 'KHMELNYTSKYI_REGION'),
    ('рівненська область', 'RIVNE_REGION'),
    ('рівненська', 'RIVNE_REGION'),
    ('волинська область', 'VOLYN_REGION'),
    ('волинська', 'VOLYN_REGION'),
    ('івано-франківська область', 'IVANO_FRANKIVSK_REGION'),
    ('івано-франківська', 'IVANO_FRANKIVSK_REGION'),
    ('тернопільська область', 'TERNOPIL_REGION'),
    ('тернопільська', 'TERNOPIL_REGION'),
    ('закарпатська область', 'ZAKARPATTIA_REGION'),
    ('закарпатська', 'ZAKARPATTIA_REGION'),
    ('чернівецька область', 'CHERNIVTSI_REGION'),
    ('чернівецька', 'CHERNIVTSI_REGION'),
    ('кіровоградська область', 'KIROVOHRAD_REGION'),
    ('кіровоградська', 'KIROVOHRAD_REGION'),
    ('херсонська область', 'KHERSON_REGION'),
    ('херсонська', 'KHERSON_REGION'),
    ('донецька область', 'DONETSK_REGION'),
    ('донецька', 'DONETSK_REGION'),
    ('луганська область', 'LUHANSK_REGION'),
    ('луганська', 'LUHANSK_REGION'),
    ('автономна республіка крим', 'CRIMEA_REGION'),
    ('м. севастополь', 'CRIMEA_REGION');
